config/routes.rb
AudIo::Application.routes.draw do
  

  root :to => "posts#index"
  
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get '/admin' => 'posts#admin'
  
  resources :posts
  resources :users

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new 
    if user.has_role? :admin
        can :manage, :all
    else
        can :read, :all
    end

  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	rolify
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :roles_users
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
	has_and_belongs_to_many :roles
	has_many :posts

	def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  	end

  	def self.from_omniauth(auth)
  		where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
	end

	def self.create_from_omniauth(auth)
  		create! do |user|
    		user.provider = auth["provider"]
    		user.uid = auth["uid"]
    		user.name = auth["info"]["nickname"]
  		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	  layout "admin", :only => [:new, :edit, :admin, :show]
  
  	prepend_before_filter do
      params[:post] &&= post_params
    end

    load_and_authorize_resource     

  	def index
		  @posts = Post.order("created_at desc").page(params[:page]).per_page(ENV['posts_per_page'].to_f)
      
      respond_to do |format|
        format.html {  render :layout => "application"} # index.html.erb
        format.js
       
      end

  	end   
  
   	def all
    	@posts = Post.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  	end

  	def new
    	@post = Post.new
  	end

  	def show
    	@post = Post.find(params[:id])
    	if request.path != post_path(@post)
      		redirect_to @post, status: :moved_permanently
    	end

  	end
  
  	def edit
   		@post = Post.find(params[:id])
  	end

  	def create
    	@post = Post.new(post_params)

    	respond_to do |format|
      		if @post.save
        		format.html { redirect_to admin_path, notice: "Post was saved" }
      		else
        		format.html { render action: "new" }
        		format.json { render json: @post.errors, status: :unprocessable_entity }
      		end
    	end
  	end
  
  	def update
    	@post = Post.find(params[:id])

    	respond_to do |format|
      		if @post.update_attributes(post_params)
        		format.html { redirect_to post_path, notice: "Post was saved" }
      		else
        		format.html { render action: "edit" }
        		format.json { render json: @post.errors, status: :unprocessable_entity }
      		end
    	end
  	end

  
  	def destroy
    	@post = Post.find(params[:id]).delete
    	redirect_to admin_path, :notice => "Post has been deleted." 
   
  	end

    private
    def post_params
      params.require(:post).permit(:title, :content, :media)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
    	auth = request.env["omniauth.auth"]
    	user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_from_omniauth(auth)
    	session[:user_id] = user.id
    	redirect_to root_url, :notice => "Signed in!"
  	end

  	def destroy
  		session[:user_id] = nil
  		redirect_to root_url, :notice => "Signed out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

<!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

     <title><%= content_for?(:title) ? yield(:title) : "Hiram's Picks" %></title>

    
    <%= javascript_include_tag :application %>
    
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="http://cdn.embed.ly/jquery.embedly-3.1.0.min.js"></script>

    <%= stylesheet_link_tag    "css/normalize" %>
    <%= stylesheet_link_tag    "css/foundation" %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <!--
    <audio autoplay="autoplay">   
      <source src="https://dl.dropboxusercontent.com/u/11548/vazqueezy.mp3" type="audio/mpeg"/>  
    </audio> -->
    <div id="user_nav">
      <% if current_user %>
        Welcome, <%= current_user.name %>!
        <%= link_to "Sign Out", signout_path %>
      <% else %>
        <%= link_to "Sign in with Twitter", "/auth/twitter" %>
      <% end %>
  </div>
    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Hiram's Picks" %></title>
  	
    <%= javascript_include_tag :application %>
    
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="http://cdn.embed.ly/jquery.embedly-3.1.0.min.js"></script>

    <%= stylesheet_link_tag    "css/normalize" %>
    <%= stylesheet_link_tag    "css/foundation" %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- <audio autoplay="autoplay">   
      <source src="https://dl.dropboxusercontent.com/u/11548/vazqueezy.mp3" type="audio/mpeg"/>  
    </audio> -->
  	<div id="user_nav">
  		<% if current_user %>
    		Welcome, <%= current_user.name %>!
        <div class="large-9 columns">
          <h6 class="subheader"><%= link_to 'Admin', admin_path %></h6>
        </div>
    		<%= link_to "Sign Out", signout_path %> 
  		<% else %>
    <!--		<%= link_to "Sign in with Twitter", "/auth/twitter" %> -->
  		<% end %>
	</div>
    <%= yield %>
   
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
== "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->"
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"

head
  meta charset="utf-8"

  / Uncomment to make IE8 render like IE7
  / meta http-equiv="X-UA-Compatible" content="IE=7"
  
  / Set the viewport width to device width for mobile
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  title= content_for?(:title) ? yield(:title) : "Untitled"

  / Included CSS Files
  = stylesheet_link_tag "application"

  / Included JS Files
  = javascript_include_tag "application"

  = csrf_meta_tag

body
  .container
    == yield

app/views/posts/_form.html.erb
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :media %>

app/views/posts/_media.html.erb
<script type="text/javascript">
$(document).ready(function() {
	
	$.embedly.defaults.key = '0098312d92ca46b9a69779ebef3f080d';
	$('.media a').embedly({query: {maxwidth: 600}, 'method':'after'});
});

</script>


<% @posts.each do |post| %>
<div class="row">
  <div class="large-12 large-offset-1 columns">
    <div class="media center inline">

      <a href="<%= post.media %>"></a>
    </div>
  </div>
</div>

<br />
<% end %>

app/views/posts/admin.html.erb
<div class="row">

    <div class="small-12 medium-8 large-6 columns medium-push-4 large-push-3">
    	<br />
    	<h1>My Posts</h1>
    	<h6 class="subheader"><%= link_to 'Go Back', root_path %></h6>
      <h6 class="subheader"><%= link_to 'New Post', new_post_path %></h6>
    	<hr />
		<% @posts.each do |post| %>
<!-- List Entries -->
      	<div class="row">
        	<div class="small-9 large-10 columns ">
          		<h2><strong><%= post.title %></strong></h2>
          		<h4 class="subheader"><%= post.content %></h4>
          		<ul class="inline-list">
            		<li><%= link_to 'View', post %></li>
            		<li><%= link_to 'Edit', edit_post_path(post) %></li>
            		<li><%= link_to 'Delete', post, :method => :delete %></li>
          		</ul>            
        	</div>
      	</div>
      	<hr />
      <!-- End List Entry -->
		<% end %>

	</div>
</div>

app/views/posts/edit.html.erb
<div class="row">

    <div class="small-12 medium-8 large-6 columns medium-push-4 large-push-3">
    	<br />
    	
    	<h1>Edit Post: <%= @post.title %></h1>
    	<hr />
		
<!-- List Entries -->
      	<div class="row">
        	<div class="small-9 large-10 columns ">
          		<%= simple_form_for @post do |f| %>  
				<%= render :partial => 'form', :locals => {:f => f} %>
				<%= f.button :submit %>
				<% end %>
          	    
        	</div>
      	</div>
      	<hr />
      <!-- End List Entry -->
	  
    	<h6 class="subheader"><%= link_to 'Go Back', admin_path %></h6>

	</div>
</div>

app/views/posts/index.html.erb
<!-- Nav Bar -->
  <br />
  <div class="row">
    <div class="large-12 columns">
      <h1 class="header"><strong>Hiram's Picks </strong> <small>This is my music. It's awesome.</small></h1>
      <hr />
    </div>
  </div>

  <!-- End Nav -->


  <!-- Main Page Content and Sidebar -->

  <div class="row">

    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">
      
  
  
      <% @posts.each do |post| %>
        <article>
          <h3 class="subheader"><%= post.title%> | <small>Posted on <%= post.created_at.strftime('%b %d') %></small></h3>
          <br />
          <br />
          <div id="render">
            <%= render 'media' %>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <h5 class="subheader"><%= post.content %></h5>
            </div>
          </div>
          <br />
          
          
          <div class="pagination-centered">
            <h4 class="subheader"><%= will_paginate @posts %></h4>
          </div>

          

          <div id="disqus_thread">
            <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
              var disqus_shortname = 'audioblog'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
              (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
              })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
            </noscript>
            <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
          </div>
      </article>

      <hr />
  <% end %>

     

    </div>

    <!-- End Main Content -->


    <!-- Sidebar -->

    <aside class="large-3 columns">
      <h5>Links</h5>
      <ul class="side-nav">
        <li><%= link_to "About.me", "http://about.me/#{ENV['social']}", :target => "_blank" %></li>
        <li><%= link_to "Spotify", "http://open.spotify.com/user/#{ENV['social']}", :target => "_blank" %></li>
        <li><%= link_to "Soundcloud", "http://soundcloud.com/#{ENV['social']}", :target => "_blank" %></li>
        <li><%= link_to "Twitter", "http://twitter.com/#{ENV['social']}", :target => "_blank" %></li>
        <li><%= link_to "Facebook", "http://facebook.com/#{ENV['social']}", :target => "_blank" %></li>
      </ul>
      <br />
      <div class="panel">
        <h5>About</h5>
        <p align="justify">First effort at creating a web app from scratch. This is a simple blog that I'll use to share music with everyone.</p>
      </div>

    </aside>

    <!-- End Sidebar -->
  </div>

  <!-- End Main Content and Sidebar -->

  

	

app/views/posts/new.html.erb
<div class="row">

    <div class="small-12 medium-8 large-6 columns medium-push-4 large-push-3">
    	<br />
    	
    	<h1>New Post</h1>
    	<hr />
		
<!-- List Entries -->
      	<div class="row">
        	<div class="small-9 large-10 columns ">
          		<%= simple_form_for @post do |f| %>  
				<%= render :partial => 'form', :locals => {:f => f} %>
				<%= f.button :submit %>
				<% end %>
          	    
        	</div>
      	</div>
      	<hr />
      <!-- End List Entry -->
	  
    	<h6 class="subheader"><%= link_to 'Go Back', admin_path %></h6>

	</div>
</div>

app/views/posts/show.html.erb
<script type="text/javascript">
$(document).ready(function() {
	
	$.embedly.defaults.key = '0098312d92ca46b9a69779ebef3f080d';
	$('.media a').embedly({query: {maxwidth: 600}, 'method':'after'});
});

</script>


<div class="row">

    <div class="small-12 medium-8 large-6 columns medium-push-4 large-push-3">
    	<br />
    	
    	<h2> <%= @post.title %></h2>
    	<hr />
    	
      	<div class="row">
        	<div class="small-9 large-10 columns ">
          		<div class="media">
				<a href="<%= @post.media %>"></a>
				</div>
        <h4 class="subheader"><%= @post.content%></h4>  	    
    </div>
</div>
<hr />
<ul class="inline-list">
  <li><h6 class="subheader"><%= link_to 'Go Back', admin_path %></h6></li>
  <li><h6 class="subheader"><%= link_to 'Edit', edit_post_path %></h6></li>
  <li><h6 class="subheader"><%= link_to 'Delete', @post, :method => :delete %></h6></li>
</ul>     
    
	</div>
</div>